# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-18 09:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showPins', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.CharField(max_length=128, null=True, verbose_name='Komentarz'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='photo_desc',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='opis zdjecia'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_desc',
            field=models.TextField(blank=True, null=True, verbose_name='kilka slow o sobie'),
        ),
    ]
