# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-19 07:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showPins', '0003_subscribe'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='user',
            name='collecion',
            field=models.IntegerField(null=True, verbose_name='Kolekcja'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=256, verbose_name='Imie'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=256, null=True, verbose_name='Nazwisko'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_desc',
            field=models.TextField(blank=True, null=True, verbose_name='Kilka slow o sobie'),
        ),
    ]
