# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-19 10:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('showPins', '0005_colection'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Colection',
            new_name='Collection',
        ),
    ]
