# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-19 10:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showPins', '0007_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='price',
            field=models.FloatField(default=1.99),
        ),
    ]
