# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-19 12:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showPins', '0008_auto_20171019_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='quantity',
            field=models.IntegerField(default=1, verbose_name='Liczba'),
        ),
        migrations.AlterField(
            model_name='card',
            name='buy_price',
            field=models.FloatField(default=99999999, verbose_name='Cena zakupy'),
        ),
    ]
