# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-19 12:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showPins', '0009_auto_20171019_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='delivery',
            field=models.IntegerField(choices=[(1, 'Odbiór osobity'), (2, 'Dostawa email'), (3, 'Przesyłka pocztowa')], default=2, verbose_name='Rodzaj dostawy'),
        ),
        migrations.AddField(
            model_name='card',
            name='delivery_target',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='suggestions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
