# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-20 10:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('showPins', '0010_auto_20171019_1248'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderId',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_cod', models.CharField(max_length=64)),
                ('add_date', models.DateField(auto_now_add=True)),
                ('total_price', models.FloatField(default=99999999, verbose_name='Cena zakupy')),
                ('delivery_target', models.CharField(blank=True, max_length=256, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='card',
            name='delivery_target',
        ),
        migrations.RemoveField(
            model_name='card',
            name='suggestions',
        ),
        migrations.AddField(
            model_name='orderid',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='showPins.Card'),
        ),
        migrations.AddField(
            model_name='orderid',
            name='photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='showPins.Photo'),
        ),
        migrations.AddField(
            model_name='orderid',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
