# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-20 10:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showPins', '0011_auto_20171020_1007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderid',
            name='card',
        ),
        migrations.RemoveField(
            model_name='orderid',
            name='order_cod',
        ),
        migrations.RemoveField(
            model_name='orderid',
            name='photo',
        ),
        migrations.AddField(
            model_name='orderid',
            name='photo',
            field=models.ManyToManyField(to='showPins.Photo'),
        ),
    ]
