# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-20 11:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showPins', '0012_auto_20171020_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderid',
            name='buy_price',
            field=models.FloatField(default=99999999, verbose_name='Cena zakupu'),
        ),
        migrations.AddField(
            model_name='orderid',
            name='delivery',
            field=models.IntegerField(choices=[(1, 'Odbiór osobity'), (2, 'Dostawa email'), (3, 'Przesyłka pocztowa')], null=True, verbose_name='Rodzaj dostawy'),
        ),
        migrations.AddField(
            model_name='orderid',
            name='quantity',
            field=models.IntegerField(default=1, verbose_name='Liczba'),
        ),
    ]
